// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quan_Ly_Lich_Lam_Viec.Data;

#nullable disable

namespace Quan_Ly_Lich_Lam_Viec.Migrations
{
    [DbContext(typeof(Quan_Li_Lich_Lam_DbContext))]
    partial class Quan_Li_Lich_Lam_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Chi_Tiet_Phan_Cong", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<bool>("Da_Xac_Nhan")
                        .HasColumnType("bit");

                    b.Property<int>("MaLich")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("Vai_Tro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaLich");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("Chi_Tiet_Phan_Cong");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Chuc_Vu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChucVu"));

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaChucVu");

                    b.ToTable("Chuc_Vu");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Dia_Diem", b =>
                {
                    b.Property<int>("MaDiaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiaDiem"));

                    b.Property<string>("DiaChiCuThe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDiaDiem");

                    b.ToTable("Dia_Diem");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Lich_Lam_Viec", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<int?>("MaDiaDiem")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiCV")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaLich");

                    b.HasIndex("MaDiaDiem");

                    b.HasIndex("MaLoaiCV");

                    b.ToTable("Lich_Lam_Viec");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Lich_Su_He_Thong", b =>
                {
                    b.Property<int>("MaLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLog"));

                    b.Property<string>("ChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLog");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("Lich_Su_He_Thong");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Loai_Cong_Viec", b =>
                {
                    b.Property<int>("MaLoaiCV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiCV"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoaiCV");

                    b.ToTable("Loai_Cong_Viec");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Nhan_Vien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaPhong");

                    b.ToTable("Nhan_Vien");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Phan_Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQuyen");

                    b.ToTable("Phan_Quyen");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Phong_Ban", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhong");

                    b.ToTable("Phong_Ban");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Tai_Khoan", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Username");

                    b.HasIndex("MaNhanVien")
                        .IsUnique();

                    b.HasIndex("MaQuyen");

                    b.ToTable("Tai_Khoan");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Tien_Do_Cong_Viec", b =>
                {
                    b.Property<int>("MaTienDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTienDo"));

                    b.Property<string>("LyDoTreHan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLich")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramHoanThanh")
                        .HasColumnType("int");

                    b.HasKey("MaTienDo");

                    b.HasIndex("MaLich");

                    b.ToTable("Tien_Do_Cong_Viec");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Chi_Tiet_Phan_Cong", b =>
                {
                    b.HasOne("Quan_Ly_Lich_Lam_Viec.Data.Lich_Lam_Viec", "Lich_Lam_Viec")
                        .WithMany("Chi_Tiet_Phan_Cong")
                        .HasForeignKey("MaLich")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quan_Ly_Lich_Lam_Viec.Data.Nhan_Vien", "Nhan_Vien")
                        .WithMany("Chi_Tiet_Phan_Cong")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lich_Lam_Viec");

                    b.Navigation("Nhan_Vien");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Lich_Lam_Viec", b =>
                {
                    b.HasOne("Quan_Ly_Lich_Lam_Viec.Data.Dia_Diem", "Dia_Diem")
                        .WithMany("LichLamViec")
                        .HasForeignKey("MaDiaDiem");

                    b.HasOne("Quan_Ly_Lich_Lam_Viec.Data.Loai_Cong_Viec", "Loai_Cong_Viec")
                        .WithMany("Lich_Lam_Viec")
                        .HasForeignKey("MaLoaiCV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dia_Diem");

                    b.Navigation("Loai_Cong_Viec");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Lich_Su_He_Thong", b =>
                {
                    b.HasOne("Quan_Ly_Lich_Lam_Viec.Data.Nhan_Vien", "Nhan_Vien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien");

                    b.Navigation("Nhan_Vien");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Nhan_Vien", b =>
                {
                    b.HasOne("Quan_Ly_Lich_Lam_Viec.Data.Chuc_Vu", "Chuc_Vu")
                        .WithMany("Nhan_Vien")
                        .HasForeignKey("MaChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quan_Ly_Lich_Lam_Viec.Data.Phong_Ban", "Phong_Ban")
                        .WithMany("Nhan_Vien")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chuc_Vu");

                    b.Navigation("Phong_Ban");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Tai_Khoan", b =>
                {
                    b.HasOne("Quan_Ly_Lich_Lam_Viec.Data.Nhan_Vien", "Nhan_Vien")
                        .WithOne("Tai_Khoan")
                        .HasForeignKey("Quan_Ly_Lich_Lam_Viec.Data.Tai_Khoan", "MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quan_Ly_Lich_Lam_Viec.Data.Phan_Quyen", "Phan_Quyen")
                        .WithMany("Tai_Khoan")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nhan_Vien");

                    b.Navigation("Phan_Quyen");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Tien_Do_Cong_Viec", b =>
                {
                    b.HasOne("Quan_Ly_Lich_Lam_Viec.Data.Lich_Lam_Viec", "Lich_Lam_Viec")
                        .WithMany("Tien_Do_Cong_Viec")
                        .HasForeignKey("MaLich")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lich_Lam_Viec");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Chuc_Vu", b =>
                {
                    b.Navigation("Nhan_Vien");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Dia_Diem", b =>
                {
                    b.Navigation("LichLamViec");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Lich_Lam_Viec", b =>
                {
                    b.Navigation("Chi_Tiet_Phan_Cong");

                    b.Navigation("Tien_Do_Cong_Viec");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Loai_Cong_Viec", b =>
                {
                    b.Navigation("Lich_Lam_Viec");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Nhan_Vien", b =>
                {
                    b.Navigation("Chi_Tiet_Phan_Cong");

                    b.Navigation("Tai_Khoan")
                        .IsRequired();
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Phan_Quyen", b =>
                {
                    b.Navigation("Tai_Khoan");
                });

            modelBuilder.Entity("Quan_Ly_Lich_Lam_Viec.Data.Phong_Ban", b =>
                {
                    b.Navigation("Nhan_Vien");
                });
#pragma warning restore 612, 618
        }
    }
}
